### ISSUE TITLE
Failing tests?

### ISSUE THREAD

**Issue by petterreinholdtsen** [trbs/rfc3161ng#11]
Hi.  When I try to run the tests using `nosetests tests/test_api.py`, I get this result:

```
E....FE
======================================================================
ERROR: test_api.default_test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: default_test() takes at least 2 arguments (0 given)

======================================================================
ERROR: test_api.test_generalized_time_decoding
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/pere/src/bitmynt/deb/python-rfc3161ng-github/tests/test_api.py", line 95, in test_generalized_time_decoding
    assert generalizedtime_to_utc_datetime('20180208181004.948468-01', False) == datetime.datetime(2018, 2, 8, 19, 10, 4, 948468, tzinfo=dateutil.tz.tzutc())
  File "/home/pere/src/bitmynt/deb/python-rfc3161ng-github/rfc3161ng/api.py", line 83, in generalizedtime_to_utc_datetime
    dt = dt.replace(tzinfo=dateutil.tz.tzoffset(name, diff if d['tz'][0] == '+' else -diff))
  File "/usr/lib/python2.7/dist-packages/dateutil/tz/tz.py", line 60, in __init__
    self._offset = datetime.timedelta(seconds=offset)
TypeError: unsupported type for timedelta seconds component: datetime.timedelta

======================================================================
FAIL: test_api.test_encode_decode_timestamp_request
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/pere/src/bitmynt/deb/python-rfc3161ng-github/tests/test_api.py", line 74, in test_encode_decode_timestamp_request
    assert tsq.prettyPrint() == "TimeStampReq:\n version=v1\n messageImprint=MessageImprint:\n  hashAlgorithm=AlgorithmIdentifier:\n   algorithm=1.3.14.3.2.26\n\n  hashedMessage=0xa94a8fe5ccb19ba61c4c0873d391e987982fbbd3\n\n certReq=False\n"
AssertionError

----------------------------------------------------------------------
Ran 7 tests in 2.834s

FAILED (errors=2, failures=1)
```

Any idea what is going wrong here?

**Comment by trbs** [comment]
committed eadbf09fc9ec9480f6b047dac6bf9aa65b4aecaa which solves the issue with nose for me and works with both Python 2.7 and 3.7 on my machine.

```
» nosetests tests/test_api.py
Verification: OK
.......
----------------------------------------------------------------------
Ran 7 tests in 3.887s

OK
```

Not sure where the errors with `dateutil` is coming from, can you try again with:

```
$ virtualenv -p python2 venv27
$ source venv27/bin/activate
$ pip install nose pytest
$ pip install pyasn1 python-dateutil pyasn1_modules requests cryptography
$ nosetests tests/test_api.py
Verification: OK
.......
----------------------------------------------------------------------
Ran 7 tests in 3.060s

OK
```

**Comment by petterreinholdtsen** [comment]
I am not too keen on running random stuff downloaded from the internet on any of my machines like pip do, so I spent some time trying to figure out how to avoid the failing tests.  The problem seem to be version dependent.  This patch get the tests working:

```
diff --git a/rfc3161ng/api.py b/rfc3161ng/api.py
index f0418d0..b85b639 100644
--- a/rfc3161ng/api.py
+++ b/rfc3161ng/api.py
@@ -76,7 +76,7 @@ def generalizedtime_to_utc_datetime(gt, naive=True):
                 diff = datetime.timedelta(
                     hours=int(d['tz'][1:3]),
                     minutes=int(d['tz'][3:5]) if len(d['tz']) > 3 else 0
-                )
+                ).total_seconds()
                 name = d['tz'][0:3]
                 if len(d['tz']) > 3:
                     name += ':' + d['tz'][3:5]
diff --git a/tests/test_api.py b/tests/test_api.py
index 50cd656..469cfc6 100755
--- a/tests/test_api.py
+++ b/tests/test_api.py
@@ -93,7 +93,7 @@ def test_teszt_e_szigno_hu_with_nonce():
 
 def test_encode_decode_timestamp_request():
     tsq = rfc3161ng.make_timestamp_request(data="test")
-    assert tsq.prettyPrint() == "TimeStampReq:\n version=v1\n messageImprint=MessageImprint:\n  hashAlgorithm=AlgorithmIdentifier:\n   algorithm=1.3.14.3.2.26\n\n  hashedMessage=0xa94a8fe5ccb19ba61c4c0873d391e987982fbbd3\n\n certReq=False\n"
+    assert tsq.prettyPrint() == "TimeStampReq:\n version='v1'\n messageImprint=MessageImprint:\n  hashAlgorithm=AlgorithmIdentifier:\n   algorithm=1.3.14.3.2.26\n\n  hashedMessage=0xa94a8fe5ccb19ba61c4c0873d391e987982fbbd3\n\n certReq='False'\n"
     bin_tsq = rfc3161ng.encode_timestamp_request(tsq)
     assert bin_tsq == b'0$\x02\x01\x010\x1f0\x07\x06\x05+\x0e\x03\x02\x1a\x04\x14\xa9J\x8f\xe5\xcc\xb1\x9b\xa6\x1cL\x08s\xd3\x91\xe9\x87\x98/\xbb\xd3'
     tsq2 = rfc3161ng.decode_timestamp_request(bin_tsq)
```

The first part make sure dateutil.tz.tzoffset() get seconds as it second argument, which seem to be what it expect here.

The second part adjust the output to match the output from prettyPrint() here.  A few single quotes is part of the output here.  Not quite sure how to rewrite this last part to work with any python version.

**Comment by petterreinholdtsen** [comment]
Here is a different proposal to handle the changed prettyPrint() output, by simpliy removing the quotes before comparing:

```
diff --git a/tests/test_api.py b/tests/test_api.py
index 50cd656..80bf1c9 100755
--- a/tests/test_api.py
+++ b/tests/test_api.py
@@ -93,7 +93,9 @@ def test_teszt_e_szigno_hu_with_nonce():
 
 def test_encode_decode_timestamp_request():
     tsq = rfc3161ng.make_timestamp_request(data="test")
-    assert tsq.prettyPrint() == "TimeStampReq:\n version=v1\n messageImprint=MessageImprint:\n  hashAlgorithm=AlgorithmIdentifier:\n   algorithm=1.3.14.3.2.26\n\n  hashedMessage=0xa94a8fe5ccb19ba61c4c0873d391e987982fbbd3\n\n certReq=False\n"
+    # Some versions of prettyPrint() include quotes, others do not.
+    # Hide the difference by removing the quotes.
+    assert tsq.prettyPrint().replace("'", "") == "TimeStampReq:\n version=v1\n messageImprint=MessageImprint:\n  hashAlgorithm=AlgorithmIdentifier:\n   algorithm=1.3.14.3.2.26\n\n  hashedMessage=0xa94a8fe5ccb19ba61c4c0873d391e987982fbbd3\n\n certReq=False\n"
     bin_tsq = rfc3161ng.encode_timestamp_request(tsq)
     assert bin_tsq == b'0$\x02\x01\x010\x1f0\x07\x06\x05+\x0e\x03\x02\x1a\x04\x14\xa9J\x8f\xe5\xcc\xb1\x9b\xa6\x1cL\x08s\xd3\x91\xe9\x87\x98/\xbb\xd3'
     tsq2 = rfc3161ng.decode_timestamp_request(bin_tsq)
```

With this change, both "nosetests3 tests/test_api.py" and "nosetests tests/test_api.py" show working tests.

**Comment by trbs** [comment]
Thanks for that fix. Looks good to add :-)

Does that fix all the `nosetests` issues for you ?

**Comment by petterreinholdtsen** [comment]
[trbs]
> Does that fix all the `nosetests` issues for you ?

Yes.
-- 
Happy hacking
Petter Reinholdtsen

**Comment by trbs** [comment]
Thanks !
